Img = {};
Img.player = new Image();
Img.player.src = '/client/img/suhaib.png';
Img.player.onload = function() {};
Img.bullet = {}
Img.bullet['magic']= new Image();
Img.bullet['magic'].src = '/client/img/bullet.png';
Img.bullet['magic'].onload = function() {};
Img.bullet['sperm']= new Image();
Img.bullet['sperm'].src = '/client/img/sperm.png';
Img.bullet['sperm'].onload = function() {};
Img.enemy = {}
Img.enemy['bat']= new Image();
Img.enemy['bat'].src = '/client/img/bat.png';
Img.enemy['bat'].onload = function(){};
Img.enemy['dildo']= new Image();
Img.enemy['dildo'].src = '/client/img/dildo.png';
Img.enemy['dildo'].onload = function(){};
Img.enemy['player']= new Image();
Img.enemy['player'].src = '/client/img/player.png';
Img.enemy['player'].onload = function(){};
